@startuml
!include ../../../theme/thoughts-uml-theme.iuml
autonumber
skinparam shadowing false
skinparam BoxPadding 25
skinparam Padding 5
skinparam minClassWidth 170
skinparam BackgroundColor #F2F2F2

hide footbox

participant User
participant Gateway
participant Sentinel
participant Controller
participant OrderAPPService
participant OrderAPPService
participant FlashOrderDomainService
participant ItemStockCacheService

participant FlashActivityAppService
participant FlashItemAppService

participant FlashItemDomainService

participant AuthService
participant SecurityService
participant Redis
participant Repository

User->Gateway:进入网关
Gateway->Sentinel:限流拦截
Sentinel->Controller:进入应用服务接口层
activate Controller
Controller->OrderAPPService:进入应用服务应用层

activate OrderAPPService
activate AuthService
OrderAPPService->AuthService:账号校验
AuthService-->OrderAPPService:返回账号校验结果
deactivate AuthService
alt  账号校验未通过
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end

OrderAPPService->DistributedLockFactoryService:获取下单锁
alt 获取锁失败
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end

activate SecurityService
OrderAPPService->SecurityService:风控与安全校验
SecurityService->OrderAPPService:返回风控校验结果
deactivate SecurityService
alt  风控校验未通过
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end
activate FlashActivityAppService
OrderAPPService -> FlashActivityAppService:根据活动配置校验是否允许下单
FlashActivityAppService --> OrderAPPService:返回校验结果
alt  活动下单校验未通过
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end
deactivate FlashActivityAppService
activate FlashItemAppService
OrderAPPService -> FlashItemAppService:根据秒杀品配置校验是否允许下单
FlashItemAppService --> OrderAPPService:返回校验结果
alt  秒杀品下单校验未通过
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end
OrderAPPService -> FlashItemAppService:获取秒杀品及配置
FlashItemAppService --> OrderAPPService:返回秒杀品配置
deactivate FlashItemAppService

activate FlashOrderDomainService
OrderAPPService -> FlashOrderDomainService:根据秒杀品活动配置校验是否允许下单
FlashOrderDomainService --> OrderAPPService:返回校验结果
alt  订单校验未通过
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end
deactivate FlashOrderDomainService

activate ItemStockCacheService
OrderAPPService->ItemStockCacheService:预扣库存
ItemStockCacheService->Redis:预扣库存
ItemStockCacheService-->OrderAPPService:返回库存校验结果
alt  预扣库存失败
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
end
deactivate ItemStockCacheService

activate FlashItemDomainService
OrderAPPService->FlashItemDomainService:执行扣库存
FlashItemDomainService-->OrderAPPService:返回库存扣减结果
alt  库存扣减失败
    activate ItemStockCacheService
    OrderAPPService -> ItemStockCacheService:恢复预扣库存
    ItemStockCacheService->Redis:恢复预扣库存
    OrderAPPService --> Controller:返回应用层结果
    Controller --> User:返回结果给用户
    deactivate ItemStockCacheService
end
activate FlashOrderDomainService
OrderAPPService->FlashOrderDomainService:创建订单
FlashOrderDomainService->Repository:订单入库
FlashOrderDomainService-->OrderAPPService:返回订单创建结果
alt 订单创建失败
    activate ItemStockCacheService
    OrderAPPService -> ItemStockCacheService:恢复预扣库存
    deactivate ItemStockCacheService
    OrderAPPService --> OrderAPPService:抛出异常回滚事务
    Controller --> User:返回结果给用户
end
deactivate FlashOrderDomainService
OrderAPPService --> Controller:返回应用层下单成功结果
Controller --> User:返回结果给用户
@enduml

